apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hg79m7wbv-python 
  janus-idp.io/tekton: hg79m7wbv-python
  backstage.io/kubernetes-id: hg79m7wbv-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hg79m7wbv-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml