apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hg79m7wbv-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hg79m7wbv-python 
  name: hg79m7wbv-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hg79m7wbv-python 
